### ISSUE TITLE
Tiled rendering backend

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#158]
For tiled rendering support, the following features need to be implemented:
- [x] Handle incoming `ADD_REQUIRED_TILES` messages
- [x] Deliver tiles in uncompressed format
- [x] Deliver tiles in ZFP compressed format (#225)
- [x] Deliver edge and corner tiles correctly (these tiles have reduced width or height)
- [ ] Handle incoming `REMOVE_REQUIRED_TILES` messages and use queueing mechanism to process tiles (#226)
- [x] Integrate correctly with animation images (#227)

**Comment by Kechil** [comment]
Note numbering clash with #158 ROI

**Comment by veggiesaurus** [comment]
removing story point estimates on this issue as they have now been assigned to the dependencies.
