### ISSUE TITLE
Backend scripting interface

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#417]
For a scripting interface, the backend needs to:

- [x] Create a gRPC service to which the [python client](https://open-bitbucket.nrao.edu/projects/CASA/repos/cartavis/browse) can connect and communicate.  The protobuf interface is defined in the python client repo.
- [x] Associate a python client session with an existing frontend session and communicate with that frontend.
- [ ] Communicate with frontend according to ICD ???

**Comment by pford** [comment]
I need requirements for the frontend/backend ICD if I am to complete the backend development.  My suggestions were in this [ICD doc](https://drive.google.com/open?id=1UApq-MMgAXU2stQ8-RjmtRkQTmNC7WxzINgX4HFjcY4).

**Comment by pford** [comment]
The frontend epic has been closed.  I fail to see how this will be completed without frontend development.

**Comment by veggiesaurus** [comment]
> I need requirements for the frontend/backend ICD if I am to complete the backend development. My suggestions were in this [ICD doc](https://drive.google.com/open?id=1UApq-MMgAXU2stQ8-RjmtRkQTmNC7WxzINgX4HFjcY4).

As discussed before, we should keep the backend/frontend interface generic, so that we don't have to adjust the ICD every time a scripting command is added. So the backend needs to translate the existing scripting calls to generic messages to send to the frontend. You can see the proposed protocol buffer messages [here](https://github.com/CARTAvis/carta-protobuf/blob/angus/generic_scripting/request/scripting.proto).

> The frontend epic has been closed. I fail to see how this will be completed without frontend development.

[#813](https://github.com/CARTAvis/carta-frontend/issues/813) is still open. Since there's only one real task for the frontend still left to do, I think it can be folded into the existing scripting epic, rather than having a separate frontend epic, but will defer to @Kechil on that.
